//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Adminler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adminler()
        {
            this.Siparisler = new HashSet<Siparisler>();
        }


        public int AdminId { get; set; }
        [Required(ErrorMessage = "Ýsim alaný gereklidir.")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Soyisim alaný gereklidir")]
        public string Soyad { get; set; }
        public string Rol { get; set; }
        [Required(ErrorMessage = "Kullanýcý adý giriniz.")]
        [DisplayName("Kullanýcý Adý")]
        public string aKullaniciAdi { get; set; }
        [Required(ErrorMessage = "Þifre giriniz.")]
        [DisplayName("Þifre")]
        public string aSifre { get; set; }
        public string AdminResim { get; set; }
        [Required(ErrorMessage = "Cinsiyet seçiniz.")]
        public string Cinsiyet { get; set; }
        public Nullable<bool> Durum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
    }
}
