//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Masalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Masalar()
        {
            this.Siparisler = new HashSet<Siparisler>();
        }

        public int MasaId { get; set; }
        [Required(ErrorMessage = "Masa adý giriniz.")]
        public string MasaAd { get; set; }
        [Required(ErrorMessage = "Kapasite giriniz.")]
        public int Kapasite { get; set; }
        [Required(ErrorMessage = "Durum alaný gereklidir.")]
        public string Durum { get; set; }
        [Required(ErrorMessage = "Konum gereklidir.")]
        public string Konum { get; set; }
        public Nullable<bool> DurumM { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
        public IEnumerable<SelectListItem> Konumlar { get; set; }
    }
}
