//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Siparisler = new HashSet<Siparisler>();
        }

        public int YemekId { get; set; }
        [Required(ErrorMessage = "Yemek adý giriniz.")]
        public string YemekAd { get; set; }
        public double YemekFiyat { get; set; }
        public string YemekResim { get; set; }
        [Required(ErrorMessage = "Kategori alaný gereklidir.")]
        public string YemekKategori { get; set; }
        public string KatalogIdler { get; set; }
        public Nullable<bool> Durum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
        public IEnumerable<SelectListItem> Kategoriler { get; set; }
    }
}
